/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Carlos
 */
public class ConsultaPres extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaPres
     */
    Connection conexion = null;
    

    public ConsultaPres() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.jpg")).getImage());
        menuAvanzado.setVisible(false);
        // rellena el desplegable de socios
        socio.removeAllItems();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/Biblioteca", "root", "");
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Socios");

            while (rs.next()) {
                socio.addItem(rs.getString(2) + " " + rs.getString(3));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertarLibro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InsertarLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        libActuales = new javax.swing.JButton();
        menuAvanzado = new javax.swing.JPanel();
        socio = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        busNumLibros = new javax.swing.JButton();
        socPasFech = new javax.swing.JToggleButton();
        volver = new javax.swing.JButton();
        libPasFech = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar prestamos");
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        libActuales.setText("Prestados Actualmente");
        libActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libActualesActionPerformed(evt);
            }
        });

        menuAvanzado.setBorder(javax.swing.BorderFactory.createTitledBorder("Nº de libros por socio"));

        jLabel1.setText("Seleciona Un Socio:");

        busNumLibros.setText("Buscar");
        busNumLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNumLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuAvanzadoLayout = new javax.swing.GroupLayout(menuAvanzado);
        menuAvanzado.setLayout(menuAvanzadoLayout);
        menuAvanzadoLayout.setHorizontalGroup(
            menuAvanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAvanzadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuAvanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(socio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuAvanzadoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAvanzadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(busNumLibros)))
                .addContainerGap())
        );
        menuAvanzadoLayout.setVerticalGroup(
            menuAvanzadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAvanzadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(socio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busNumLibros)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        socPasFech.setText("Busqueda por socio");
        socPasFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socPasFechActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        libPasFech.setText("Libros pasados de fecha");
        libPasFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libPasFechActionPerformed(evt);
            }
        });

        jButton1.setText("Socios con libros atrasados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(libActuales, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(libPasFech)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(volver)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuAvanzado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(socPasFech)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuAvanzado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(socPasFech))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(libActuales, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addComponent(libPasFech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libActualesActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/Biblioteca", "root", "");
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT libros.Titulo, socios.nombre, socios.apellidos FROM libros, prestamos, socios  "
                    + "WHERE prestamos.id_Libro = libros.id AND prestamos.id_socio = socios.id");
            jTextArea1.setText("");
            while (rs.next()) {
                jTextArea1.append("Libro: " + rs.getString(1)
                        + "\n" + "Prestado a: " + rs.getString(2)
                        + " " + rs.getString(3) + "\n -----------------------"
                        + "---------------------- \n");
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ConsultaPres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_libActualesActionPerformed

    private void socPasFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socPasFechActionPerformed
        // TODO add your handling code here:
        if (socPasFech.isSelected()) {
            menuAvanzado.setVisible(true);
        } else if (!socPasFech.isSelected()) {
            menuAvanzado.setVisible(false);
        }
    }//GEN-LAST:event_socPasFechActionPerformed

    private void busNumLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNumLibrosActionPerformed
        String sSocio = (String) socio.getSelectedItem();
        String querysSQL = "SELECT id FROM Socios WHERE Nombre = ? AND Apellidos LIKE ?";
        String nombre[];
        nombre = sSocio.split(" ");
        String nombre2 = nombre[0];
        String apellidos = nombre[1];
        int idSocio = 0;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/Biblioteca", "root", "");
            Statement st = conexion.createStatement();
            //busca el id del usuario seleccionado
            PreparedStatement ps2 = conexion.prepareStatement(querysSQL);
            ps2.setString(1, nombre2);
            ps2.setString(2, apellidos + "%");
            ResultSet rs2 = ps2.executeQuery();
            while (rs2.next()) {
                idSocio = rs2.getInt(1);
            }

            // crea la queery para saber el numero de libros
            ResultSet rs = st.executeQuery("SELECT COUNT(id_libro) FROM prestamos WHERE id_socio = " + idSocio + ";");

            //ejecutamos la query del rs
            while (rs.next()) {
                jTextArea1.setText("Numero de libros prestados a " + sSocio + " es de: " + rs.getInt(1));
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ConsultaPres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_busNumLibrosActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(rootPaneCheckingEnabled);
        dispose();
    }//GEN-LAST:event_volverActionPerformed


    private void libPasFechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libPasFechActionPerformed
        jTextArea1.setText("");
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/Biblioteca", "root", "");
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT libros.titulo FROM prestamos, libros WHERE fech_fin <=CURDATE()");

            while (rs.next()) {
                jTextArea1.append("Titulo: " + rs.getString(1) + "\n --------------------- \n");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ConsultaPres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_libPasFechActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/Biblioteca", "root", "");
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT socios.nombre, socios.apellidos FROM prestamos, socios WHERE fech_fin <=CURDATE()");

            while (rs.next()) {
                jTextArea1.append("Nombre: " + rs.getString(1) + "\nApellidos: " + rs.getString(2) + "\n --------------------- \n");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ConsultaPres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busNumLibros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton libActuales;
    private javax.swing.JButton libPasFech;
    private javax.swing.JPanel menuAvanzado;
    private javax.swing.JToggleButton socPasFech;
    private javax.swing.JComboBox socio;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
